format = """
[░▒](#a89984)\
[ ▲ ](bg:#a89984 fg:#282828)\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$php\
$time\
\n$character"""

[directory]
style = "fg:#ebdbb2 bg:#458588"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol $branch ](fg:#83a598 bg:#282828)]($style)'

[git_status]
style = "bg:#282828"
format = '[[($all_status$ahead_behind )](fg:#83a598 bg:#282828)]($style)'

[python]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($virtualenv $version) ](fg:#d79921 bg:#282828)]($style)'

[nodejs]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#b8bb26 bg:#282828)]($style)'

[rust]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#d65d0e bg:#282828)]($style)'

[golang]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#689d6a bg:#282828)]($style)'

[php]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#b16286 bg:#282828)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#282828"
format = '[[  $time ](fg:#83a598 bg:#282828)]($style)'
